exclude: [
  "build_site.sh",
  "LICENSE_pixyll.txt",
]

# Site settings
title:       Reed Swiernik
email:       reed.swiernik@gmail.com
author:      Reed Swiernik
description: "A place for me to write about technical topics and other random things."
baseurl:     ""
url:         "http://reedswiernik.com"

# Google analytics
google_analytics: true

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: reedswiernik

# Social icons
github_username: rswiernik
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username: reedswiernik
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems: [jekyll-paginate]
#  - jekyll-sitemap
